version: '3'
services:
  workflow_queue:
    build:
      context: ${WORKFLOW_DIR:-.}
      dockerfile: Dockerfile.rabbitmq
    image: openfido/dev-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbit-user
      RABBITMQ_DEFAULT_PASS: rabbit-password
      RABBITMQ_DEFAULT_VHOST: api-queue
  workflow_db:
    image: postgres:11
    environment:
      POSTGRES_DB: workflowservice
      POSTGRES_PASSWORD: dev-password
  workflowstorage:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio123
    volumes:
      - ${WORKFLOW_DIR:-.}/uploads:/data:delegated
    ports:
      - "9000:9000"
  workflow_service:
    build: ${WORKFLOW_DIR:-.}
    image: openfido/dev-workflow
    command: flask run -h 0.0.0.0
    environment:
      PGDATABASE: workflowservice
      PGUSER: postgres
      PGHOST: workflow_db
      FLASK_APP: run.py
      FLASK_ENV: development
      SECRET_KEY: local-dev-db
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:dev-password@workflow_db/workflowservice
      CELERY_BROKER_URL: amqp://rabbit-user:rabbit-password@workflow_queue/api-queue
      S3_ACCESS_KEY_ID: minio_access_key
      S3_SECRET_ACCESS_KEY: minio123
      S3_ENDPOINT_URL: http://workflowstorage:9000
    volumes:
      - ${WORKFLOW_DIR:-.}:/opt/app:delegated
    ports:
      - "${WORKFLOW_PORT:-5000}:5000"
    depends_on:
      - workflow_db
      - workflow_queue
      - workflowstorage
  workflow_worker:
    build:
      context: ${WORKFLOW_DIR:-.}
      dockerfile: Dockerfile.worker
    image: openfido/dev-workflow-worker
    command: celery -A app.worker worker -l DEBUG
    environment:
      CELERY_BROKER_URL: amqp://rabbit-user:rabbit-password@workflow_queue/api-queue
      WORKER_API_SERVER: http://workflow_service:${WORKFLOW_PORT:-5000}
      S3_ACCESS_KEY_ID: minio_access_key
      S3_SECRET_ACCESS_KEY: minio123
      S3_ENDPOINT_URL: http://workflowstorage:9000
    env_file:
      - ${WORKFLOW_DIR:-.}/.worker-env
    volumes:
      - ${WORKFLOW_DIR:-.}:/opt/app:delegated
      - /var/run/docker.sock:/var/run/docker.sock
      # The 'docker in docker' nature of this local configuration means that
      # bind mounts happen on the 'host docker' not the first docker container.
      # Make temp directories on the main host (otherwise files cannot be
      # found).
      - /tmp:/tmp
    depends_on:
      - workflow_queue
      - workflow_service
      - workflowstorage
