name: generic_converters_env
dependencies:
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py38_0
  - click=7.0=py_0
  - flask=1.1.1=py_0
  - itsdangerous=1.1.0=py_0
  - jinja2=2.10.3=py_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - markupsafe=1.1.1=py38h1de35cc_0
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1d=h1de35cc_3
  - pip=19.3.1=py38_0
  - python=3.8.0=h359304d_2
  - readline=7.0=h1de35cc_5
  - setuptools=44.0.0=py38_0
  - sqlite=3.30.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py38_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
