version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@1.3.0
jobs:
  test:
    docker:
      - image: python:3.8
    environment:
      PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/my-project
    steps:
      - checkout
      - run:
          command: |
            apt-get update -qq
            apt-get install -y pipenv
            pip install virtualenv
      - restore_cache:
          keys:
            - project-pipfile-{{ checksum "Pipfile.lock" }}
      - run:
          command: pipenv install --dev
      - save_cache:
          key: project-pipfile-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv
      - run:
          command: |
            mkdir test-results
            pipenv run invoke test --junit --enforce-percent 99
      - store_test_results:
          path: test-results
      - run:
          command: pipenv run invoke style
      - run:
          command: pipenv run invoke lint --fail-under=9
  build-docker:
    docker:
      - image: circleci/python:3.8
    environment:
      DOCKER_BUILDKIT: "1"
    steps:
      - setup_remote_docker:
          version: 18.09.3
      - aws-ecr/build-and-push-image:
          tag: "$CIRCLE_BRANCH"
          repo: openfido/dev-workflow_service
          extra-build-args: "--ssh default"
workflows:
  test_build_and_push:
    jobs:
      - test
      - build-docker:
          requires:
            - test
